import Navbar from "../components/Navbar";
import {Roboto} from 'next/font/google';

export const metadata = {
  title: 'Mi tienda con Next.js',
  description: 'Generated by Next.js',
  keywords: 'tienda, next, js',
}

const roboto = Roboto({
  weight:["300"],
  subsets: ['latin'],
  style:["italic", "normal"]
})

export default function RootLayout({ children }) {
  return <html>
    <head>
      <title>My App</title>
    </head>
    <body className={roboto.className}>
      <Navbar/>
      {children}
    </body>
  </html>
}
